services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: v5ultra
      POSTGRES_PASSWORD: password
      POSTGRES_DB: v5ultra
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U v5ultra"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
