name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 18, cache: 'pnpm' }
      - run: pnpm -v && pnpm install --frozen-lockfile
      - run: pnpm -w lint && pnpm -w typecheck && pnpm -w test
      - run: pnpm --filter web build
      - run: pnpm -w openapi:generate && pnpm -w sdk:build
      - run: pnpm -w golden:all
      - run: pnpm -w a11y || true
      - run: bash scripts/ci/prelogin-guard-web.sh

  build-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with: { node-version: 18, cache: 'pnpm' }
      - run: pnpm -v && pnpm install --frozen-lockfile
      - run: pnpm --filter mobile lint || true
      - run: pnpm --filter mobile typecheck || true
      - run: pnpm --filter mobile test
      - run: pnpm --filter mobile expo:doctor || true
      - run: pnpm --filter mobile expo:export:test || true
      - run: bash scripts/ci/prelogin-guard-mobile.sh

name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm -v
      - run: pnpm install --frozen-lockfile

      - name: Run checks and gates
        run: |
          pnpm -w lint
          pnpm -w typecheck
          pnpm -w test
          pnpm -w cov
          pnpm -w a11y
          pnpm -w gate:phase0
          pnpm -w gate:phase1
          pnpm -w gate:phase2
      - run: pnpm -w gate:phase3
