name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'

      - run: pnpm -v
      - run: pnpm install --frozen-lockfile

      - name: Run checks and gates
        run: |
          pnpm -w lint
          pnpm -w typecheck
          pnpm -w test
          pnpm -w cov
          pnpm -w a11y
          pnpm -w gate:phase0
          pnpm -w gate:phase1
          pnpm -w gate:phase2
      - run: pnpm -w gate:phase3
      - run: pnpm -w gate:phase4
