on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm -w lint
      - run: pnpm -w typecheck
      - run: pnpm -w test
      - run: pnpm -w cov
      - run: pnpm -w a11y
      - run: pnpm -w sbom
      - run: pnpm -w gate:phase0

      - name: Start DB services
        run: |
          docker --version
          docker compose version || true
          echo "DATABASE_URL=postgresql://app:app@localhost:5432/v5" >> $GITHUB_ENV
          echo "REDIS_URL=redis://localhost:6379" >> $GITHUB_ENV
          docker compose up -d
          docker compose ps
      - name: Prisma generate
        run: pnpm prisma:generate
      - name: Prisma validate
        run: pnpm prisma:validate
      - name: Healthcheck
        run: node scripts/healthcheck.cjs
      - name: Stop DB services
        if: always()
        run: docker compose down -v
