name: ZAP Baseline

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Next.js dev server
        run: |
          corepack enable
          pnpm install --frozen-lockfile
          pnpm --filter "./apps/web" dev &
          echo $! > .tmp/dev.pid
          sleep 10
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          allow_issue_writing: false
          rules_file_name: '.zap/rules.tsv'
        continue-on-error: true
      - name: Stop dev server
        run: |
          kill $(cat .tmp/dev.pid) || true
