-- AlterTable
ALTER TABLE "public"."Opportunity" ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "updatedAt" DROP NOT NULL,
ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "public"."OpportunityPlan" ALTER COLUMN "steps" SET DATA TYPE JSON,
ALTER COLUMN "risks" SET DATA TYPE JSON,
ALTER COLUMN "acceptanceCriteria" SET DATA TYPE JSON,
ALTER COLUMN "createdAt" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "public"."OpportunityDecision" ALTER COLUMN "decidedAt" DROP NOT NULL,
ALTER COLUMN "decidedAt" SET DATA TYPE TIMESTAMP(6);

